image: registry.gitlab.com/itk.fr/lorhammer/build

before_script:
    - ln -s /builds/$CI_PROJECT_PATH /go/src/lorhammer
    - cd /go/src/lorhammer

stages:
    - lint
    - test
    - integration
    - compile
    - doc

lint:
    stage: lint
    script:
        - make lint

test:unit:
    stage: test
    script:
        - make test

test:coverage:
    stage: test
    coverage: /total[^\d]+(\d+.\d+\%)/
    script:
        - make cover

test:docker:
  stage: test
  services:
    - docker:dind
  script:
    - make dep
    - ./resources/scripts/buildAllEnv.sh -light --snapshot
    - docker build -t "${CI_REGISTRY_IMAGE}/lorhammer:${CI_PIPELINE_ID}" -f docker/lorhammer/Dockerfile-lorhammer .
    - docker build -t "${CI_REGISTRY_IMAGE}/orchestrator:${CI_PIPELINE_ID}" -f docker/lorhammer/Dockerfile-orchestrator .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push "${CI_REGISTRY_IMAGE}/lorhammer:${CI_PIPELINE_ID}"
    - docker push "${CI_REGISTRY_IMAGE}/orchestrator:${CI_PIPELINE_ID}"
  variables:
    DOCKER_HOST: "tcp://docker:2375"

.integration: &integration
  stage: integration
  services:
    - docker:dind
  script:
    - LORHAMMER_PROMETHEUS_IP="prometheus" LORHAMMER_MQTT_IP="mqtt" LORHAMMER_CONSUL_IP="consul" LORHAMMER_GRAFANA_IP="grafana" ./resources/scripts/launchTools.sh
    - sleep 10
    - echo "Start 1 lorhammer"
    - docker-compose -f docker-compose.yml -f docker-compose.integration.yml -p ${CI_JOB_ID} up -d lorhammer
    - sleep 30
    - echo "Start orchestrator to launch scenario and check all is ok"
    - docker-compose -f docker-compose.yml -f docker-compose.integration.yml -p ${CI_JOB_ID} run orchestrator
  after_script:
    - docker-compose -p ${CI_JOB_ID} down --remove-orphans
  tags:
    - docker

integration:oneShot:
  <<: *integration
  variables:
    FROM_FILE: "./resources/scenarios/ci/ci-integration-oneShot.json"
    DOCKER_HOST: "tcp://docker:2375"
    COMPOSE_HTTP_TIMEOUT: "200"

integration:ramp:
  <<: *integration
  variables:
    FROM_FILE: "./resources/scenarios/ci/ci-integration-ramp.json"
    DOCKER_HOST: "tcp://docker:2375"
    COMPOSE_HTTP_TIMEOUT: "200"

integration:repeat:
  <<: *integration
  variables:
    FROM_FILE: "./resources/scenarios/ci/ci-integration-repeat.json"
    DOCKER_HOST: "tcp://docker:2375"
    COMPOSE_HTTP_TIMEOUT: "200"

compile:all:
  stage: compile
  services:
    - docker:dind
  script:
    - make dep
    - ./resources/scripts/buildAllEnv.sh -full --snapshot
  only:
    - master@itk.fr/lorhammer
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  variables:
    DOCKER_HOST: "tcp://docker:2375"

compile:docker:lorhammer:
  stage: compile
  services:
    - docker:dind
  script:
    - make dep
    - ./resources/scripts/buildAllEnv.sh -light --snapshot
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/lorhammer -f docker/lorhammer/Dockerfile-lorhammer .
    - docker push $CI_REGISTRY_IMAGE/lorhammer
  only:
    - master@itk.fr/lorhammer
  variables:
    DOCKER_HOST: "tcp://docker:2375"

compile:docker:orchestrator:
  stage: compile
  services:
    - docker:dind
  script:
    - make dep
    - ./resources/scripts/buildAllEnv.sh -light --snapshot
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/orchestrator -f docker/lorhammer/Dockerfile-orchestrator .
    - docker push $CI_REGISTRY_IMAGE/orchestrator
  only:
    - master@itk.fr/lorhammer
  variables:
    DOCKER_HOST: "tcp://docker:2375"

compile:tag:
  stage: compile
  services:
    - docker:dind
  script:
    - make dep
    - ./resources/scripts/buildAllEnv.sh -full
  only:
    - tags
  artifacts:
    paths:
      - dist
  variables:
    DOCKER_HOST: "tcp://docker:2375"

compile:docker-tag:lorhammer:
  stage: compile
  services:
    - docker:dind
  script:
    - make dep
    - ./resources/scripts/buildAllEnv.sh -light
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE/lorhammer:${CI_COMMIT_REF_NAME}" -f docker/lorhammer/Dockerfile-lorhammer .
    - docker push "$CI_REGISTRY_IMAGE/lorhammer:${CI_COMMIT_REF_NAME}"
  only:
    - tags
  variables:
    DOCKER_HOST: "tcp://docker:2375"

compile:docker-tag:orchestrator:
  stage: compile
  services:
    - docker:dind
  script:
    - make dep
    - ./resources/scripts/buildAllEnv.sh -light
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE/orchestrator:${CI_COMMIT_REF_NAME}" -f docker/lorhammer/Dockerfile-orchestrator .
    - docker push "$CI_REGISTRY_IMAGE/orchestrator:${CI_COMMIT_REF_NAME}"
  only:
    - tags
  variables:
    DOCKER_HOST: "tcp://docker:2375"

pages:
  stage: doc
  script:
    - make doc
  artifacts:
    paths:
      - public
  only:
    - master
